 spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: root
    password: root
    properties:
        mail:
            smtp:              
                auth: true
                starttls:
                    enable: true
 #Configuraci\u00f3n MySQL
  datasource: 
    url: jdbc:mysql://localhost:3306/disney?allowPublicKeyRetrieval=true&useSSL=false&useTimezone=true&serverTimezone=GMT&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver 
#Configuracion Creacion de tablas (Hibernate)
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect      
#Que thymeleaf no guarde datos en cache
  thymeleaf:
    cache: false 
  main:
    banner-mode: off

